# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cam_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cam_gui(object):
    def setupUi(self, cam_gui):
        cam_gui.setObjectName("cam_gui")
        cam_gui.resize(840, 667)
        self.centralWidget = QtWidgets.QWidget(cam_gui)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, -1, 821, 611))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 791, 81))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 2, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 2, 1, 1, 1)
        self.doubleSpinBox_Exp_Time = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_Exp_Time.setFont(font)
        self.doubleSpinBox_Exp_Time.setMinimum(0.0)
        self.doubleSpinBox_Exp_Time.setMaximum(5.0)
        self.doubleSpinBox_Exp_Time.setSingleStep(0.1)
        self.doubleSpinBox_Exp_Time.setObjectName("doubleSpinBox_Exp_Time")
        self.gridLayout_7.addWidget(self.doubleSpinBox_Exp_Time, 1, 2, 1, 1)
        self.label_Exp_time_disp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Exp_time_disp.setFont(font)
        self.label_Exp_time_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Exp_time_disp.setObjectName("label_Exp_time_disp")
        self.gridLayout_7.addWidget(self.label_Exp_time_disp, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 7, 1, 1, 6)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 791, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_Cooler_OnOff = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Cooler_OnOff.setFont(font)
        self.label_Cooler_OnOff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Cooler_OnOff.setObjectName("label_Cooler_OnOff")
        self.gridLayout_5.addWidget(self.label_Cooler_OnOff, 1, 1, 1, 1)
        self.label_Temp_disp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Temp_disp.setFont(font)
        self.label_Temp_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Temp_disp.setObjectName("label_Temp_disp")
        self.gridLayout_5.addWidget(self.label_Temp_disp, 1, 0, 1, 1)
        self.doubleSpinBox_Temp_set = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_Temp_set.setFont(font)
        self.doubleSpinBox_Temp_set.setDecimals(0)
        self.doubleSpinBox_Temp_set.setMinimum(-70.0)
        self.doubleSpinBox_Temp_set.setMaximum(30.0)
        self.doubleSpinBox_Temp_set.setProperty("value", -30.0)
        self.doubleSpinBox_Temp_set.setObjectName("doubleSpinBox_Temp_set")
        self.gridLayout_5.addWidget(self.doubleSpinBox_Temp_set, 1, 2, 1, 1)
        self.pushButton_Temp_set = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Temp_set.setFont(font)
        self.pushButton_Temp_set.setObjectName("pushButton_Temp_set")
        self.gridLayout_5.addWidget(self.pushButton_Temp_set, 1, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 0, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem12, 2, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 2, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 2, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem15, 2, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 6, 1, 1, 6)
        self.pushButton_Save = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.gridLayout.addWidget(self.pushButton_Save, 9, 6, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem16, 9, 0, 1, 1)
        self.pushButton_Snap = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Snap.setFont(font)
        self.pushButton_Snap.setObjectName("pushButton_Snap")
        self.gridLayout.addWidget(self.pushButton_Snap, 9, 5, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 10, 391, 120))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem17, 3, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem18, 3, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem19, 0, 1, 1, 1)
        self.label_Acq_mode = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Acq_mode.setFont(font)
        self.label_Acq_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Acq_mode.setObjectName("label_Acq_mode")
        self.gridLayout_9.addWidget(self.label_Acq_mode, 1, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem20, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem21, 2, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem22, 2, 1, 1, 1)
        self.lineEdit_acq_mode = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_acq_mode.setObjectName("lineEdit_acq_mode")
        self.gridLayout_9.addWidget(self.lineEdit_acq_mode, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 5, 1, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 4, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem23, 7, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem24, 8, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem25, 2, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem26, 5, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem27, 6, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem28, 0, 4, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem29, 0, 5, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem30, 0, 6, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem31, 0, 2, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem32, 0, 3, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem33, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 10, 391, 80))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem34, 2, 1, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem35, 0, 1, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem36, 2, 0, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem37, 0, 0, 1, 1)
        self.label_Read_mode = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Read_mode.setFont(font)
        self.label_Read_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Read_mode.setObjectName("label_Read_mode")
        self.gridLayout_10.addWidget(self.label_Read_mode, 1, 0, 1, 1)
        self.lineEdit_read_mode = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_read_mode.setObjectName("lineEdit_read_mode")
        self.gridLayout_10.addWidget(self.lineEdit_read_mode, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 5, 4, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 791, 81))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem38, 2, 1, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem39, 2, 2, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem40, 0, 3, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem41, 2, 3, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem42, 0, 2, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem43, 0, 0, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem44, 2, 0, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem45, 0, 1, 1, 1)
        self.doubleSpinBox_EMCCD_Gain = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_EMCCD_Gain.setFont(font)
        self.doubleSpinBox_EMCCD_Gain.setDecimals(0)
        self.doubleSpinBox_EMCCD_Gain.setMaximum(300.0)
        self.doubleSpinBox_EMCCD_Gain.setObjectName("doubleSpinBox_EMCCD_Gain")
        self.gridLayout_8.addWidget(self.doubleSpinBox_EMCCD_Gain, 1, 2, 1, 1)
        self.label_EMCCDGain_disp = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_EMCCDGain_disp.setFont(font)
        self.label_EMCCDGain_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_EMCCDGain_disp.setObjectName("label_EMCCDGain_disp")
        self.gridLayout_8.addWidget(self.label_EMCCDGain_disp, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 8, 1, 1, 6)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 3, 1, 1)
        self.label_Cam_OnOff = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Cam_OnOff.setFont(font)
        self.label_Cam_OnOff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Cam_OnOff.setObjectName("label_Cam_OnOff")
        self.gridLayout.addWidget(self.label_Cam_OnOff, 2, 4, 1, 1)
        self.pushButton_Cam_On = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Cam_On.setFont(font)
        self.pushButton_Cam_On.setObjectName("pushButton_Cam_On")
        self.gridLayout.addWidget(self.pushButton_Cam_On, 2, 5, 1, 1)
        self.pushButton_Cam_Off = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Cam_Off.setFont(font)
        self.pushButton_Cam_Off.setObjectName("pushButton_Cam_Off")
        self.gridLayout.addWidget(self.pushButton_Cam_Off, 2, 6, 1, 1)
        cam_gui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(cam_gui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 840, 21))
        self.menuBar.setObjectName("menuBar")
        cam_gui.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(cam_gui)
        self.mainToolBar.setObjectName("mainToolBar")
        cam_gui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(cam_gui)
        self.statusBar.setObjectName("statusBar")
        cam_gui.setStatusBar(self.statusBar)

        self.retranslateUi(cam_gui)
        QtCore.QMetaObject.connectSlotsByName(cam_gui)

    def retranslateUi(self, cam_gui):
        _translate = QtCore.QCoreApplication.translate
        cam_gui.setWindowTitle(_translate("cam_gui", "cam_gui"))
        self.groupBox_2.setTitle(_translate("cam_gui", "Exposure Time"))
        self.label_Exp_time_disp.setText(_translate("cam_gui", "0 s"))
        self.groupBox.setTitle(_translate("cam_gui", "Temperature"))
        self.label_Cooler_OnOff.setText(_translate("cam_gui", "OFF"))
        self.label_Temp_disp.setText(_translate("cam_gui", "0 °C"))
        self.pushButton_Temp_set.setText(_translate("cam_gui", "Set"))
        self.pushButton_Save.setText(_translate("cam_gui", "Save"))
        self.pushButton_Snap.setText(_translate("cam_gui", "Snap"))
        self.groupBox_4.setTitle(_translate("cam_gui", "Acquisition Mode"))
        self.label_Acq_mode.setText(_translate("cam_gui", "N/A"))
        self.label_6.setText(_translate("cam_gui", "Picture:"))
        self.groupBox_5.setTitle(_translate("cam_gui", "Read Mode"))
        self.label_Read_mode.setText(_translate("cam_gui", "N/A"))
        self.groupBox_3.setTitle(_translate("cam_gui", "EMCCD Gain"))
        self.label_EMCCDGain_disp.setText(_translate("cam_gui", "0"))
        self.label.setText(_translate("cam_gui", "Initialisation:"))
        self.label_Cam_OnOff.setText(_translate("cam_gui", "OFF"))
        self.pushButton_Cam_On.setText(_translate("cam_gui", "Camera ON"))
        self.pushButton_Cam_Off.setText(_translate("cam_gui", "Camera OFF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cam_gui = QtWidgets.QMainWindow()
    ui = Ui_cam_gui()
    ui.setupUi(cam_gui)
    cam_gui.show()
    sys.exit(app.exec_())

