# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cam_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cam_gui(object):
    def setupUi(self, cam_gui):
        cam_gui.setObjectName("cam_gui")
        cam_gui.resize(508, 557)
        self.centralWidget = QtWidgets.QWidget(cam_gui)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, -1, 481, 501))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Temp_set = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Temp_set.setFont(font)
        self.pushButton_Temp_set.setObjectName("pushButton_Temp_set")
        self.gridLayout.addWidget(self.pushButton_Temp_set, 2, 4, 1, 1)
        self.doubleSpinBox_Temp_set = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_Temp_set.setFont(font)
        self.doubleSpinBox_Temp_set.setDecimals(0)
        self.doubleSpinBox_Temp_set.setMinimum(-60.0)
        self.doubleSpinBox_Temp_set.setMaximum(30.0)
        self.doubleSpinBox_Temp_set.setProperty("value", -30.0)
        self.doubleSpinBox_Temp_set.setObjectName("doubleSpinBox_Temp_set")
        self.gridLayout.addWidget(self.doubleSpinBox_Temp_set, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.doubleSpinBox_Exp_Time = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_Exp_Time.setFont(font)
        self.doubleSpinBox_Exp_Time.setMinimum(0.0)
        self.doubleSpinBox_Exp_Time.setMaximum(5.0)
        self.doubleSpinBox_Exp_Time.setSingleStep(0.1)
        self.doubleSpinBox_Exp_Time.setObjectName("doubleSpinBox_Exp_Time")
        self.gridLayout.addWidget(self.doubleSpinBox_Exp_Time, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.doubleSpinBox_EMCCD_Gain = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doubleSpinBox_EMCCD_Gain.setFont(font)
        self.doubleSpinBox_EMCCD_Gain.setDecimals(0)
        self.doubleSpinBox_EMCCD_Gain.setMaximum(300.0)
        self.doubleSpinBox_EMCCD_Gain.setObjectName("doubleSpinBox_EMCCD_Gain")
        self.gridLayout.addWidget(self.doubleSpinBox_EMCCD_Gain, 5, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.pushButton_Save = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.gridLayout.addWidget(self.pushButton_Save, 6, 4, 1, 1)
        self.pushButton_Snap = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Snap.setFont(font)
        self.pushButton_Snap.setObjectName("pushButton_Snap")
        self.gridLayout.addWidget(self.pushButton_Snap, 6, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.pushButton_Cam_OnOff = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Cam_OnOff.setFont(font)
        self.pushButton_Cam_OnOff.setObjectName("pushButton_Cam_OnOff")
        self.gridLayout.addWidget(self.pushButton_Cam_OnOff, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 2, 1, 1)
        self.label_Cam_OnOff = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Cam_OnOff.setFont(font)
        self.label_Cam_OnOff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Cam_OnOff.setObjectName("label_Cam_OnOff")
        self.gridLayout.addWidget(self.label_Cam_OnOff, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 2, 1, 1)
        self.label_Cooler_OnOff = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Cooler_OnOff.setFont(font)
        self.label_Cooler_OnOff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Cooler_OnOff.setObjectName("label_Cooler_OnOff")
        self.gridLayout.addWidget(self.label_Cooler_OnOff, 3, 4, 1, 1)
        
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 3, 1, 1)
        self.label_Temp_disp = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Temp_disp.setFont(font)
        self.label_Temp_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Temp_disp.setObjectName("label_Temp_disp")
        self.gridLayout.addWidget(self.label_Temp_disp, 3, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 4, 1, 1)
        cam_gui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(cam_gui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 508, 21))
        self.menuBar.setObjectName("menuBar")
        cam_gui.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(cam_gui)
        self.mainToolBar.setObjectName("mainToolBar")
        cam_gui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(cam_gui)
        self.statusBar.setObjectName("statusBar")
        cam_gui.setStatusBar(self.statusBar)

        self.retranslateUi(cam_gui)
        QtCore.QMetaObject.connectSlotsByName(cam_gui)

    def retranslateUi(self, cam_gui):
        _translate = QtCore.QCoreApplication.translate
        cam_gui.setWindowTitle(_translate("cam_gui", "cam_gui"))
        self.pushButton_Temp_set.setText(_translate("cam_gui", "Set"))
        self.label_6.setText(_translate("cam_gui", "Picture:"))
        self.label.setText(_translate("cam_gui", "Initialisation:"))
        self.pushButton_Save.setText(_translate("cam_gui", "Save"))
        self.pushButton_Snap.setText(_translate("cam_gui", "Snap"))
        self.label_2.setText(_translate("cam_gui", "Temperature set:"))
        self.label_4.setText(_translate("cam_gui", "Exposure Time:"))
        self.label_3.setText(_translate("cam_gui", "Temperature:"))
        self.pushButton_Cam_OnOff.setText(_translate("cam_gui", "Camera"))
        self.label_5.setText(_translate("cam_gui", "EMCCD Gain:"))
        self.label_Cam_OnOff.setText(_translate("cam_gui", "OFF"))
        self.label_Cooler_OnOff.setText(_translate("cam_gui", "OFF"))
        self.label_Temp_disp.setText(_translate("cam_gui", "0 °C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cam_gui = QtWidgets.QMainWindow()
    ui = Ui_cam_gui()
    ui.setupUi(cam_gui)
    cam_gui.show()
    sys.exit(app.exec_())

